### ISSUE TITLE
Lỗi sau khi cài đặt thành công

### ISSUE THREAD

**Issue by hoanglongvnpt** [dangdinhtu2014/nukeviet_photo#1]
Mình đã cài đặt thành công module của bạn, đã thêm ảnh và đã kích hoạt block module.block_detail nhưng bị thông báo lỗi sau:
 Thông báo từ Hệ thống

Nên chú ý Nên chú ý: Undefined index: thumb in file /modules/photo/blocks/module.block_detail.php on line 75

Nên chú ý Nên chú ý: Undefined index: total_rating in file /modules/photo/blocks/module.block_detail.php on line 89

Nên chú ý Nên chú ý: Undefined index: total_rating in file /modules/photo/blocks/module.block_detail.php on line 91

Nên chú ý Nên chú ý: Undefined index: click_rating in file /modules/photo/blocks/module.block_detail.php on line 92

Nên chú ý Nên chú ý: Undefined index: total_rating in file /modules/photo/blocks/module.block_detail.php on line 93

Nên chú ý Nên chú ý: Undefined index: album_id in file /modules/photo/blocks/module.block_detail.php on line 95

Nên chú ý Nên chú ý: Undefined index: capturedate in file /modules/photo/blocks/module.block_detail.php on line 97
Rất mong được hướng dẫn khắc phục. Thank bạn!
![899](https://cloud.githubusercontent.com/assets/11238423/6424434/11f4e93e-bf2c-11e4-909d-b6db6f9f3cca.PNG)

**Comment by dangdinhtu2014** [comment]
đã fix
