### ISSUE TITLE
Không hiển thị trang photo

### ISSUE THREAD

**Issue by anhutbeo** [dangdinhtu2014/nukeviet_photo#4]
Đã thêm album, thêm ảnh thành công nhưng trang chủ photo không hiển thị báo lỗi \
Thông báo từ Hệ thống
Nên chú ý Nên chú ý: Undefined index: thumb in file /modules/photo/blocks/module.block_detail.php on line 76
Nên chú ý Nên chú ý: Undefined index: total_rating in file /modules/photo/blocks/module.block_detail.php on line 90
Nên chú ý Nên chú ý: Undefined index: total_rating in file /modules/photo/blocks/module.block_detail.php on line 92
Nên chú ý Nên chú ý: Undefined index: click_rating in file /modules/photo/blocks/module.block_detail.php on line 93
Nên chú ý Nên chú ý: Undefined index: total_rating in file /modules/photo/blocks/module.block_detail.php on line 94
Nên chú ý Nên chú ý: Undefined index: album_id in file /modules/photo/blocks/module.block_detail.php on line 96
Nên chú ý Nên chú ý: Undefined index: capturedate in file /modules/photo/blocks/module.block_detail.php on line 98

**Comment by dangdinhtu2014** [comment]
đã fix. Bạn tải phiên bản mới về để cài lại. Xoá bản cũ đi nhé
